import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/common/provider";
import { Navbar } from "@/components/navbar";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reviwer CV",
  description: "Generated by Reem Ebrahim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta
          name="google-site-verification"
          content="X4JUofDq1_SmhdRGJlnch_ewQIj4DmKtUb7z7vXP3C8"
        />

      </head>
      <body className="min-h-full flex flex-col">
        <Providers>
          <div className="flex flex-col flex-1  ">
            <Navbar />
            <div className="flex w-full min-h-screen">
              <div className="flex-1">{children}</div>
              <div className="hidden md:block w-[40%] h-screen sticky top-0  overflow-hidden">
                <Image
                  src="/people-are-reviewing.jpg"
                  fill
                  alt="people"
                  className="object-cover"
                />

                {/* WAVE CUT */}
                <div className="absolute top-0 left-0 h-full w-full">
                  <svg
                    className="h-full w-full"
                    viewBox="0 0 100 100"
                    preserveAspectRatio="none"
                  >
                    <path
                      d="M0,0 L40,0 C10,10 20,60 40,100 L0,100 Z"
                      fill="#b5bb36"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
